---
site_name: Zappy documentation
nav:
  - Home: index.md
  - Network (Shared): network.md
  - Server:
      - Overview: server/index.md
      - Architecture: server/architecture.md
      - Core Orchestrator: server/core.md
      - Game Engine: server/game_engine.md
  - AI:
      - Overview: ai/index.md
  - GUI:
      - Overview: gui/index.md
      - Architecture: gui/architecture.md
      - Core Orchestrator: gui/core.md
      - User Interface: gui/ui.md
      - Rendering: gui/rendering.md
      - Networking: gui/network.md
      - Events: gui/events.md
theme:
  name: readthedocs
plugins:
  - search
  - mermaid2
