name: CTest

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  CCACHE_DIR: ${{ github.workspace }}/.ccache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ctest:
    name: Run CTest
    runs-on: self-hosted
    container: 'epitechcontent/epitest-docker'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential cmake libmbedtls-dev libssh2-1-dev libconfig++-dev ccache
      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ github.ref }}-
            ccache-
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Run CTest
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure --output-junit results.xml
      - name: Summary Test Results
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "build/results.xml"
