name: Linter
on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]
permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    name: Check code style with clang-format and clang-tidy
    runs-on: self-hosted
    container: 'epitechcontent/epitest-docker'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential cmake clang-format-20 clang-tidy-20 libconfig++-dev libmbedtls-dev libssh2-1-dev
      - name: Configure CMake
        run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '22'
          style: 'file'
          tidy-checks: ''
          database: 'build'
          ignore: '.github|libs'
      - name: Fail fast if checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
